-- テスト: Supabase Branching の自動適用確認用
-- 確認後に削除する

CREATE TABLE IF NOT EXISTS public.branching_test (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message text NOT NULL DEFAULT 'branching works',
  created_at timestamptz NOT NULL DEFAULT now()
);
