-- ============================================================
-- Sprint 5: SV-1 アンケート関連テーブル作成
-- ============================================================

-- ============================================================
-- 1. survey_responses（アンケート回答）
-- ============================================================
CREATE TABLE public.survey_responses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id uuid NOT NULL REFERENCES public.bookings(id),
  customer_user_id bigint NOT NULL REFERENCES public.users(id),
  provider_id bigint NOT NULL REFERENCES public.providers(id),
  csat smallint NOT NULL CHECK (csat BETWEEN 1 AND 5),
  driver_service smallint CHECK (driver_service BETWEEN 1 AND 5),
  driver_quality smallint CHECK (driver_quality BETWEEN 1 AND 5),
  driver_price smallint CHECK (driver_price BETWEEN 1 AND 5),
  comment text,
  review_text text,
  review_public boolean NOT NULL DEFAULT false,
  review_visible boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX survey_responses_booking_id_key ON public.survey_responses USING btree (booking_id);
CREATE INDEX idx_survey_responses_provider ON public.survey_responses USING btree (provider_id);
CREATE INDEX idx_survey_responses_customer ON public.survey_responses USING btree (customer_user_id);

-- ============================================================
-- 2. survey_template_questions（業界別テンプレート設問マスタ）
-- ============================================================
CREATE TABLE public.survey_template_questions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category text NOT NULL,
  question_text text NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_survey_template_questions_category ON public.survey_template_questions USING btree (category);

-- ============================================================
-- 3. provider_survey_settings（事業主が選んだ追加テンプレート設問）
-- ============================================================
CREATE TABLE public.provider_survey_settings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider_id bigint NOT NULL REFERENCES public.providers(id),
  template_question_id bigint NOT NULL REFERENCES public.survey_template_questions(id),
  custom_text text,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (provider_id, template_question_id)
);

CREATE INDEX idx_provider_survey_settings_provider ON public.provider_survey_settings USING btree (provider_id);

-- ============================================================
-- 4. pending_survey_notifications（送信キュー）
-- ============================================================
CREATE TABLE public.pending_survey_notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id uuid NOT NULL REFERENCES public.bookings(id),
  customer_user_id bigint NOT NULL REFERENCES public.users(id),
  provider_id bigint NOT NULL REFERENCES public.providers(id),
  scheduled_at timestamptz NOT NULL,
  sent_at timestamptz,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'sent', 'failed')),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX pending_survey_notifications_booking_id_key ON public.pending_survey_notifications USING btree (booking_id);
CREATE INDEX idx_pending_survey_status ON public.pending_survey_notifications USING btree (status, scheduled_at);

-- ============================================================
-- 5. customer_visit_counts（訪問回数管理）
-- ============================================================
CREATE TABLE public.customer_visit_counts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_user_id bigint NOT NULL REFERENCES public.users(id),
  provider_id bigint NOT NULL REFERENCES public.providers(id),
  visit_count integer NOT NULL DEFAULT 0,
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (customer_user_id, provider_id)
);

CREATE INDEX idx_customer_visit_counts_customer ON public.customer_visit_counts USING btree (customer_user_id);

-- ============================================================
-- 6. RLS ポリシー
-- ============================================================

-- survey_responses
ALTER TABLE public.survey_responses ENABLE ROW LEVEL SECURITY;

CREATE POLICY survey_responses_select_own ON public.survey_responses
  FOR SELECT USING (
    customer_user_id IN (SELECT id FROM users WHERE auth_uid = auth.uid())
  );

CREATE POLICY survey_responses_select_provider ON public.survey_responses
  FOR SELECT USING (
    provider_id IN (SELECT p.id FROM providers p JOIN users u ON u.id = p.user_id WHERE u.auth_uid = auth.uid())
  );

CREATE POLICY survey_responses_insert_own ON public.survey_responses
  FOR INSERT WITH CHECK (
    customer_user_id IN (SELECT id FROM users WHERE auth_uid = auth.uid())
  );

CREATE POLICY survey_responses_delete_own ON public.survey_responses
  FOR DELETE USING (
    customer_user_id IN (SELECT id FROM users WHERE auth_uid = auth.uid())
  );

-- survey_responses: 公開レビューは誰でも参照可能
CREATE POLICY survey_responses_select_public ON public.survey_responses
  FOR SELECT USING (
    review_public = true AND review_visible = true
  );

-- survey_responses: 事業主がvisibleを更新可能
CREATE POLICY survey_responses_update_provider ON public.survey_responses
  FOR UPDATE USING (
    provider_id IN (SELECT p.id FROM providers p JOIN users u ON u.id = p.user_id WHERE u.auth_uid = auth.uid())
  );

-- survey_template_questions
ALTER TABLE public.survey_template_questions ENABLE ROW LEVEL SECURITY;

CREATE POLICY survey_template_questions_select_all ON public.survey_template_questions
  FOR SELECT USING (true);

-- provider_survey_settings
ALTER TABLE public.provider_survey_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY provider_survey_settings_select_own ON public.provider_survey_settings
  FOR SELECT USING (
    provider_id IN (SELECT p.id FROM providers p JOIN users u ON u.id = p.user_id WHERE u.auth_uid = auth.uid())
  );

CREATE POLICY provider_survey_settings_insert_own ON public.provider_survey_settings
  FOR INSERT WITH CHECK (
    provider_id IN (SELECT p.id FROM providers p JOIN users u ON u.id = p.user_id WHERE u.auth_uid = auth.uid())
  );

CREATE POLICY provider_survey_settings_update_own ON public.provider_survey_settings
  FOR UPDATE USING (
    provider_id IN (SELECT p.id FROM providers p JOIN users u ON u.id = p.user_id WHERE u.auth_uid = auth.uid())
  );

CREATE POLICY provider_survey_settings_delete_own ON public.provider_survey_settings
  FOR DELETE USING (
    provider_id IN (SELECT p.id FROM providers p JOIN users u ON u.id = p.user_id WHERE u.auth_uid = auth.uid())
  );

-- pending_survey_notifications
ALTER TABLE public.pending_survey_notifications ENABLE ROW LEVEL SECURITY;

CREATE POLICY pending_survey_notifications_select_own ON public.pending_survey_notifications
  FOR SELECT USING (
    customer_user_id IN (SELECT id FROM users WHERE auth_uid = auth.uid())
  );

-- customer_visit_counts
ALTER TABLE public.customer_visit_counts ENABLE ROW LEVEL SECURITY;

CREATE POLICY customer_visit_counts_select_own ON public.customer_visit_counts
  FOR SELECT USING (
    customer_user_id IN (SELECT id FROM users WHERE auth_uid = auth.uid())
  );

-- ============================================================
-- 7. get_provider_profile RPC にレビュー情報を追加
-- ============================================================
CREATE OR REPLACE FUNCTION public.get_provider_profile(p_slug text)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
declare
  v_result json;
begin
  select json_build_object(
    'id', p.id,
    'slug', p.slug,
    'name', p.name,
    'bio', p.bio,
    'icon_url', p.icon_url,
    'line_contact_url', p.line_contact_url,
    'contact_email', p.contact_email,
    'brand_color', coalesce(p.brand_color, '#6366f1'),
    'category', p.category,
    'subscription_status', p.subscription_status,
    'review_summary', (
      select json_build_object(
        'avg_csat', round(avg(sr.csat)::numeric, 1),
        'count', count(*)
      )
      from public.survey_responses sr
      where sr.provider_id = p.id
        and sr.review_public = true
        and sr.review_visible = true
        and sr.review_text is not null
        and sr.review_text <> ''
    ),
    'csat_summary', (
      select json_build_object(
        'avg_csat', round(avg(sr.csat)::numeric, 1),
        'count', count(*)
      )
      from public.survey_responses sr
      where sr.provider_id = p.id
    ),
    'recent_reviews', coalesce((
      select json_agg(r order by r.created_at desc)
      from (
        select
          sr.id,
          sr.csat,
          sr.review_text,
          sr.created_at,
          u.display_name as customer_name
        from public.survey_responses sr
        join public.users u on u.id = sr.customer_user_id
        where sr.provider_id = p.id
          and sr.review_public = true
          and sr.review_visible = true
          and sr.review_text is not null
          and sr.review_text <> ''
        order by sr.created_at desc
        limit 3
      ) r
    ), '[]'::json),
    'services', coalesce((
      select json_agg(
        json_build_object(
          'id', s.id,
          'name', s.name,
          'caption', s.caption,
          'description', s.description,
          'duration_min', s.duration_min,
          'price', s.price,
          'custom_fields', s.custom_fields
        ) order by s.sort_order
      )
      from public.services s
      where s.provider_id = p.id and s.is_published = true
    ), '[]'::json)
  ) into v_result
  from public.providers p
  where p.slug = p_slug and p.is_active = true;

  return v_result;
end;
$$;

-- ============================================================
-- 8. search_providers RPC にCSAT情報を追加
-- ============================================================
CREATE OR REPLACE FUNCTION public.search_providers(
  p_categories text[] DEFAULT NULL,
  p_query text DEFAULT NULL,
  p_offset integer DEFAULT 0,
  p_limit integer DEFAULT 20
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
declare
  v_result json;
begin
  select json_agg(row_to_json(t)) into v_result
  from (
    select
      p.slug,
      p.name,
      p.bio,
      p.icon_url,
      p.category,
      p.brand_color,
      (
        select round(avg(sr.csat)::numeric, 1)
        from public.survey_responses sr
        where sr.provider_id = p.id
      ) as avg_csat,
      (
        select count(*)::integer
        from public.survey_responses sr
        where sr.provider_id = p.id
          and sr.review_public = true
          and sr.review_visible = true
          and sr.review_text is not null
          and sr.review_text <> ''
      ) as review_count
    from public.providers p
    where p.is_active = true
      and exists (
        select 1 from public.services s
        where s.provider_id = p.id and s.is_published = true
      )
      and (p_categories is null or p.category = any(p_categories))
      and (
        p_query is null
        or p.name ilike '%' || p_query || '%'
        or p.bio ilike '%' || p_query || '%'
      )
    order by p.id desc
    offset p_offset
    limit p_limit
  ) t;

  return coalesce(v_result, '[]'::json);
end;
$$;

-- ============================================================
-- 9. get_provider_reviews RPC（全件取得）
-- ============================================================
CREATE OR REPLACE FUNCTION public.get_provider_reviews(
  p_slug text,
  p_offset integer DEFAULT 0,
  p_limit integer DEFAULT 20
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
declare
  v_result json;
  v_provider_id bigint;
begin
  select id into v_provider_id
  from public.providers
  where slug = p_slug and is_active = true;

  if v_provider_id is null then
    return '[]'::json;
  end if;

  select json_agg(row_to_json(t)) into v_result
  from (
    select
      sr.id,
      sr.csat,
      sr.review_text,
      sr.created_at,
      u.display_name as customer_name
    from public.survey_responses sr
    join public.users u on u.id = sr.customer_user_id
    where sr.provider_id = v_provider_id
      and sr.review_public = true
      and sr.review_visible = true
      and sr.review_text is not null
      and sr.review_text <> ''
    order by sr.created_at desc
    offset p_offset
    limit p_limit
  ) t;

  return coalesce(v_result, '[]'::json);
end;
$$;
