-- ============================================================
-- EdgeConnect (peco) - Initial Schema
-- Exported from Supabase project: people-connect (Mumbai)
-- Date: 2026-04-25
-- ============================================================

-- ============================================================
-- 1. TABLES
-- ============================================================

-- users
CREATE TABLE public.users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  line_user_id text NOT NULL,
  display_name text,
  role text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  auth_uid uuid,
  is_line_friend boolean NOT NULL DEFAULT false,
  customer_name text,
  customer_phone text
);

CREATE UNIQUE INDEX users_line_user_id_key ON public.users USING btree (line_user_id);
CREATE UNIQUE INDEX users_auth_uid_key ON public.users USING btree (auth_uid);

-- providers
CREATE TABLE public.providers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES public.users(id),
  slug text NOT NULL,
  name text,
  bio text,
  icon_url text,
  line_contact_url text,
  is_active boolean NOT NULL DEFAULT true,
  calendar_token text,
  calendar_last_synced_at timestamptz,
  contact_email text,
  brand_color text DEFAULT '#6366f1'::text,
  category text,
  contact_phone text
);

CREATE UNIQUE INDEX providers_slug_key ON public.providers USING btree (slug);

-- provider_settings
CREATE TABLE public.provider_settings (
  provider_id bigint NOT NULL PRIMARY KEY REFERENCES public.providers(id),
  interval_before_min integer NOT NULL DEFAULT 0,
  interval_after_min integer NOT NULL DEFAULT 0,
  business_hours jsonb,
  slot_step_min integer NOT NULL DEFAULT 30
);

-- services
CREATE TABLE public.services (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider_id bigint NOT NULL REFERENCES public.providers(id),
  name text NOT NULL,
  description text,
  duration_min integer NOT NULL,
  price integer NOT NULL DEFAULT 0,
  is_published boolean NOT NULL DEFAULT false,
  cancel_deadline_hours integer NOT NULL DEFAULT 24,
  cancel_policy_note text,
  custom_fields jsonb,
  sort_order integer NOT NULL DEFAULT 0,
  caption text
);

-- bookings
CREATE TABLE public.bookings (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  provider_id bigint NOT NULL REFERENCES public.providers(id),
  service_id bigint NOT NULL REFERENCES public.services(id),
  customer_user_id bigint NOT NULL REFERENCES public.users(id),
  start_at timestamptz NOT NULL,
  end_at timestamptz NOT NULL,
  status text NOT NULL DEFAULT 'confirmed'::text,
  cancelled_by text,
  created_at timestamptz NOT NULL DEFAULT now(),
  customer_name text,
  customer_phone text,
  custom_answers jsonb
);

CREATE INDEX idx_bookings_provider_start_status ON public.bookings USING btree (provider_id, start_at, status);

-- blocked_slots
CREATE TABLE public.blocked_slots (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider_id bigint NOT NULL REFERENCES public.providers(id),
  start_at timestamptz NOT NULL,
  end_at timestamptz NOT NULL,
  reason text
);

-- categories
CREATE TABLE public.categories (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  value text NOT NULL,
  label text NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX categories_value_key ON public.categories USING btree (value);

-- ============================================================
-- 2. VIEWS
-- ============================================================

CREATE VIEW public.providers_public AS
  SELECT id, slug, name, bio, icon_url, is_active
  FROM providers
  WHERE is_active = true;

-- ============================================================
-- 3. RLS (Row Level Security)
-- ============================================================

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.providers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.provider_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blocked_slots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

-- users
CREATE POLICY users_select_own ON public.users FOR SELECT USING (auth.uid() = auth_uid);
CREATE POLICY users_update_own ON public.users FOR UPDATE USING (auth.uid() = auth_uid);

-- providers
CREATE POLICY providers_select_public ON public.providers FOR SELECT USING (true);
CREATE POLICY providers_select_own ON public.providers FOR SELECT USING (
  user_id IN (SELECT id FROM users WHERE auth_uid = auth.uid())
);
CREATE POLICY providers_insert_own ON public.providers FOR INSERT WITH CHECK (
  user_id IN (SELECT id FROM users WHERE auth_uid = auth.uid())
);
CREATE POLICY providers_update_own ON public.providers FOR UPDATE USING (
  user_id IN (SELECT id FROM users WHERE auth_uid = auth.uid())
);

-- provider_settings
CREATE POLICY provider_settings_select_authenticated ON public.provider_settings FOR SELECT TO authenticated USING (true);
CREATE POLICY provider_settings_select_own ON public.provider_settings FOR SELECT USING (
  provider_id IN (SELECT p.id FROM providers p JOIN users u ON u.id = p.user_id WHERE u.auth_uid = auth.uid())
);
CREATE POLICY provider_settings_insert_own ON public.provider_settings FOR INSERT WITH CHECK (
  provider_id IN (SELECT p.id FROM providers p JOIN users u ON u.id = p.user_id WHERE u.auth_uid = auth.uid())
);
CREATE POLICY provider_settings_update_own ON public.provider_settings FOR UPDATE USING (
  provider_id IN (SELECT p.id FROM providers p JOIN users u ON u.id = p.user_id WHERE u.auth_uid = auth.uid())
);

-- services
CREATE POLICY services_select_published ON public.services FOR SELECT USING (is_published = true);
CREATE POLICY services_select_own ON public.services FOR SELECT USING (
  provider_id IN (SELECT p.id FROM providers p JOIN users u ON u.id = p.user_id WHERE u.auth_uid = auth.uid())
);
CREATE POLICY services_insert_own ON public.services FOR INSERT WITH CHECK (
  provider_id IN (SELECT p.id FROM providers p JOIN users u ON u.id = p.user_id WHERE u.auth_uid = auth.uid())
);
CREATE POLICY services_update_own ON public.services FOR UPDATE USING (
  provider_id IN (SELECT p.id FROM providers p JOIN users u ON u.id = p.user_id WHERE u.auth_uid = auth.uid())
);
CREATE POLICY services_delete_own ON public.services FOR DELETE USING (
  provider_id IN (SELECT p.id FROM providers p JOIN users u ON u.id = p.user_id WHERE u.auth_uid = auth.uid())
);

-- bookings
CREATE POLICY bookings_select_customer ON public.bookings FOR SELECT USING (
  customer_user_id IN (SELECT id FROM users WHERE auth_uid = auth.uid())
);
CREATE POLICY bookings_select_provider ON public.bookings FOR SELECT USING (
  provider_id IN (SELECT p.id FROM providers p JOIN users u ON u.id = p.user_id WHERE u.auth_uid = auth.uid())
);
CREATE POLICY bookings_insert_customer ON public.bookings FOR INSERT WITH CHECK (
  customer_user_id IN (SELECT id FROM users WHERE auth_uid = auth.uid())
);
CREATE POLICY bookings_update_customer ON public.bookings FOR UPDATE USING (
  customer_user_id IN (SELECT id FROM users WHERE auth_uid = auth.uid())
);
CREATE POLICY bookings_update_provider ON public.bookings FOR UPDATE USING (
  provider_id IN (SELECT p.id FROM providers p JOIN users u ON u.id = p.user_id WHERE u.auth_uid = auth.uid())
);

-- blocked_slots
CREATE POLICY blocked_slots_select_own ON public.blocked_slots FOR SELECT USING (
  provider_id IN (SELECT p.id FROM providers p JOIN users u ON u.id = p.user_id WHERE u.auth_uid = auth.uid())
);
CREATE POLICY blocked_slots_insert_own ON public.blocked_slots FOR INSERT WITH CHECK (
  provider_id IN (SELECT p.id FROM providers p JOIN users u ON u.id = p.user_id WHERE u.auth_uid = auth.uid())
);
CREATE POLICY blocked_slots_update_own ON public.blocked_slots FOR UPDATE USING (
  provider_id IN (SELECT p.id FROM providers p JOIN users u ON u.id = p.user_id WHERE u.auth_uid = auth.uid())
);
CREATE POLICY blocked_slots_delete_own ON public.blocked_slots FOR DELETE USING (
  provider_id IN (SELECT p.id FROM providers p JOIN users u ON u.id = p.user_id WHERE u.auth_uid = auth.uid())
);

-- categories
CREATE POLICY categories_read ON public.categories FOR SELECT USING (true);

-- ============================================================
-- 4. FUNCTIONS
-- ============================================================

-- upsert_user_from_line (with auth_uid)
CREATE OR REPLACE FUNCTION public.upsert_user_from_line(
  p_line_user_id text,
  p_display_name text,
  p_role text DEFAULT 'customer',
  p_auth_uid uuid DEFAULT NULL
)
RETURNS users
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
declare
  v_user public.users;
begin
  if p_line_user_id is null or p_line_user_id = '' then
    raise exception 'line_user_id is required';
  end if;

  if p_role not in ('provider', 'customer') then
    raise exception 'role must be provider or customer';
  end if;

  insert into public.users (line_user_id, display_name, role, auth_uid)
  values (p_line_user_id, p_display_name, p_role, p_auth_uid)
  on conflict (line_user_id) do update
    set display_name = excluded.display_name,
        auth_uid = coalesce(excluded.auth_uid, users.auth_uid)
  returning * into v_user;

  return v_user;
end;
$$;

-- register_provider (with contact_email)
CREATE OR REPLACE FUNCTION public.register_provider(
  p_line_user_id text,
  p_slug text,
  p_name text,
  p_line_contact_url text DEFAULT NULL,
  p_contact_email text DEFAULT NULL,
  p_bio text DEFAULT NULL,
  p_icon_url text DEFAULT NULL
)
RETURNS providers
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public', 'extensions'
AS $$
declare
  v_user public.users;
  v_provider public.providers;
  v_default_hours jsonb;
begin
  select * into v_user from public.users
    where line_user_id = p_line_user_id;

  if v_user is null then
    raise exception 'User not found for line_user_id: %', p_line_user_id;
  end if;

  update public.users set role = 'provider' where id = v_user.id;

  if p_slug !~ '^[a-z0-9][a-z0-9\\-]{1,48}[a-z0-9]$' then
    raise exception 'slug must be 3-50 chars, lowercase alphanumeric and hyphens only';
  end if;

  insert into public.providers (user_id, slug, name, bio, icon_url, line_contact_url, contact_email, calendar_token)
  values (v_user.id, p_slug, p_name, p_bio, p_icon_url, p_line_contact_url, p_contact_email, encode(extensions.gen_random_bytes(32), 'hex'))
  returning * into v_provider;

  v_default_hours := '{
    "0": null,
    "1": {"open": "09:00", "close": "18:00"},
    "2": {"open": "09:00", "close": "18:00"},
    "3": {"open": "09:00", "close": "18:00"},
    "4": {"open": "09:00", "close": "18:00"},
    "5": {"open": "09:00", "close": "18:00"},
    "6": null
  }'::jsonb;

  insert into public.provider_settings (provider_id, business_hours)
  values (v_provider.id, v_default_hours);

  return v_provider;
end;
$$;

-- create_booking (with custom fields)
CREATE OR REPLACE FUNCTION public.create_booking(
  p_provider_id integer,
  p_service_id integer,
  p_customer_line_user_id text,
  p_start_at timestamptz,
  p_customer_name text DEFAULT NULL,
  p_customer_phone text DEFAULT NULL,
  p_custom_answers jsonb DEFAULT NULL
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
declare
  v_customer public.users;
  v_service public.services;
  v_settings public.provider_settings;
  v_end_at timestamptz;
  v_block_start timestamptz;
  v_block_end timestamptz;
  v_booking_id uuid;
begin
  select * into v_customer from public.users
    where line_user_id = p_customer_line_user_id;

  if v_customer is null then
    raise exception 'Customer not found';
  end if;

  select * into v_service from public.services
    where id = p_service_id
      and provider_id = p_provider_id
      and is_published = true;

  if v_service is null then
    raise exception 'Service not found or not published';
  end if;

  select * into v_settings from public.provider_settings
    where provider_id = p_provider_id;

  v_end_at := p_start_at + (v_service.duration_min || ' minutes')::interval;

  v_block_start := p_start_at - (coalesce(v_settings.interval_before_min, 0) || ' minutes')::interval;
  v_block_end := v_end_at + (coalesce(v_settings.interval_after_min, 0) || ' minutes')::interval;

  perform 1
  from public.bookings
  where provider_id = p_provider_id
    and status = 'confirmed'
    and start_at < v_block_end
    and end_at > v_block_start
  for update;

  if found then
    raise exception 'Time slot is not available';
  end if;

  perform 1
  from public.blocked_slots
  where provider_id = p_provider_id
    and start_at < v_end_at
    and end_at > p_start_at;

  if found then
    raise exception 'Time slot is blocked';
  end if;

  insert into public.bookings (
    provider_id, service_id, customer_user_id, start_at, end_at,
    customer_name, customer_phone, custom_answers
  )
  values (
    p_provider_id, p_service_id, v_customer.id, p_start_at, v_end_at,
    p_customer_name, p_customer_phone, p_custom_answers
  )
  returning id into v_booking_id;

  return json_build_object('id', v_booking_id);
end;
$$;

-- cancel_booking
CREATE OR REPLACE FUNCTION public.cancel_booking(
  p_booking_id uuid,
  p_line_user_id text
)
RETURNS bookings
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
declare
  v_user public.users;
  v_booking public.bookings;
  v_service public.services;
  v_cancelled_by text;
begin
  select * into v_user from public.users
    where line_user_id = p_line_user_id;

  if v_user is null then
    raise exception 'User not found';
  end if;

  select * into v_booking from public.bookings
    where id = p_booking_id
    for update;

  if v_booking is null then
    raise exception 'Booking not found';
  end if;

  if v_booking.status = 'cancelled' then
    raise exception 'Booking is already cancelled';
  end if;

  if v_booking.customer_user_id = v_user.id then
    v_cancelled_by := 'customer';

    select * into v_service from public.services where id = v_booking.service_id;

    if v_service is not null
      and v_booking.start_at - (v_service.cancel_deadline_hours || ' hours')::interval < now() then
      raise exception 'Cancellation deadline has passed';
    end if;

  elsif exists (
    select 1 from public.providers
      where id = v_booking.provider_id and user_id = v_user.id
  ) then
    v_cancelled_by := 'provider';
  else
    raise exception 'Not authorized to cancel this booking';
  end if;

  update public.bookings
    set status = 'cancelled', cancelled_by = v_cancelled_by
    where id = p_booking_id
  returning * into v_booking;

  return v_booking;
end;
$$;

-- get_provider_profile
CREATE OR REPLACE FUNCTION public.get_provider_profile(p_slug text)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
declare
  v_result json;
begin
  select json_build_object(
    'id', p.id,
    'slug', p.slug,
    'name', p.name,
    'bio', p.bio,
    'icon_url', p.icon_url,
    'line_contact_url', p.line_contact_url,
    'contact_email', p.contact_email,
    'brand_color', coalesce(p.brand_color, '#6366f1'),
    'category', p.category,
    'services', coalesce((
      select json_agg(
        json_build_object(
          'id', s.id,
          'name', s.name,
          'caption', s.caption,
          'description', s.description,
          'duration_min', s.duration_min,
          'price', s.price,
          'custom_fields', s.custom_fields
        ) order by s.sort_order
      )
      from public.services s
      where s.provider_id = p.id and s.is_published = true
    ), '[]'::json)
  ) into v_result
  from public.providers p
  where p.slug = p_slug and p.is_active = true;

  return v_result;
end;
$$;

-- get_available_dates
CREATE OR REPLACE FUNCTION public.get_available_dates(
  p_provider_id integer,
  p_service_id integer,
  p_start_date date,
  p_end_date date
)
RETURNS TABLE(available_date date)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
declare
  v_service public.services;
  v_settings public.provider_settings;
  v_current_date date;
  v_day_of_week int;
  v_hours jsonb;
  v_open_time time;
  v_close_time time;
  v_slot_start timestamptz;
  v_slot_end timestamptz;
  v_interval_before interval;
  v_interval_after interval;
  v_step interval;
  v_has_slot boolean;
begin
  select * into v_service from public.services
    where id = p_service_id and provider_id = p_provider_id and is_published = true;

  if v_service is null then
    return;
  end if;

  select * into v_settings from public.provider_settings
    where provider_id = p_provider_id;

  if v_settings is null or v_settings.business_hours is null then
    return;
  end if;

  v_interval_before := (coalesce(v_settings.interval_before_min, 0) || ' minutes')::interval;
  v_interval_after := (coalesce(v_settings.interval_after_min, 0) || ' minutes')::interval;
  v_step := (coalesce(v_settings.slot_step_min, 30) || ' minutes')::interval;

  v_current_date := p_start_date;

  while v_current_date <= p_end_date loop
    v_has_slot := false;

    if v_current_date <= current_date then
      v_current_date := v_current_date + 1;
      continue;
    end if;

    v_day_of_week := extract(dow from v_current_date);

    v_hours := v_settings.business_hours -> v_day_of_week::text;

    if v_hours is not null and (v_hours ->> 'open') is not null then
      v_open_time := (v_hours ->> 'open')::time;
      v_close_time := (v_hours ->> 'close')::time;

      v_slot_start := (v_current_date || ' ' || v_open_time)::timestamp at time zone 'Asia/Tokyo';

      while v_slot_start + (v_service.duration_min || ' minutes')::interval
            <= (v_current_date || ' ' || v_close_time)::timestamp at time zone 'Asia/Tokyo' loop
        v_slot_end := v_slot_start + (v_service.duration_min || ' minutes')::interval;

        if not exists (
          select 1 from public.bookings
          where provider_id = p_provider_id
            and status = 'confirmed'
            and start_at < v_slot_end + v_interval_after
            and end_at > v_slot_start - v_interval_before
        ) and not exists (
          select 1 from public.blocked_slots
          where provider_id = p_provider_id
            and start_at < v_slot_end
            and end_at > v_slot_start
        ) and v_slot_start > now() then
          v_has_slot := true;
          exit;
        end if;

        v_slot_start := v_slot_start + v_step;
      end loop;
    end if;

    if v_has_slot then
      available_date := v_current_date;
      return next;
    end if;

    v_current_date := v_current_date + 1;
  end loop;
end;
$$;

-- get_available_slots
CREATE OR REPLACE FUNCTION public.get_available_slots(
  p_provider_id integer,
  p_service_id integer,
  p_date date
)
RETURNS TABLE(slot_start timestamptz, slot_end timestamptz)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
declare
  v_service public.services;
  v_settings public.provider_settings;
  v_day_of_week int;
  v_hours jsonb;
  v_open_time time;
  v_close_time time;
  v_slot_start timestamptz;
  v_slot_end timestamptz;
  v_interval_before interval;
  v_interval_after interval;
  v_step interval;
begin
  select * into v_service from public.services
    where id = p_service_id and provider_id = p_provider_id and is_published = true;

  if v_service is null then
    return;
  end if;

  select * into v_settings from public.provider_settings
    where provider_id = p_provider_id;

  if v_settings is null or v_settings.business_hours is null then
    return;
  end if;

  v_interval_before := (coalesce(v_settings.interval_before_min, 0) || ' minutes')::interval;
  v_interval_after := (coalesce(v_settings.interval_after_min, 0) || ' minutes')::interval;
  v_step := (coalesce(v_settings.slot_step_min, 30) || ' minutes')::interval;

  v_day_of_week := extract(dow from p_date);

  v_hours := v_settings.business_hours -> v_day_of_week::text;

  if v_hours is null or (v_hours ->> 'open') is null then
    return;
  end if;

  v_open_time := (v_hours ->> 'open')::time;
  v_close_time := (v_hours ->> 'close')::time;

  v_slot_start := (p_date || ' ' || v_open_time)::timestamp at time zone 'Asia/Tokyo';

  while v_slot_start + (v_service.duration_min || ' minutes')::interval
        <= (p_date || ' ' || v_close_time)::timestamp at time zone 'Asia/Tokyo' loop
    v_slot_end := v_slot_start + (v_service.duration_min || ' minutes')::interval;

    if not exists (
      select 1 from public.bookings
      where provider_id = p_provider_id
        and status = 'confirmed'
        and start_at < v_slot_end + v_interval_after
        and end_at > v_slot_start - v_interval_before
    ) and not exists (
      select 1 from public.blocked_slots
      where provider_id = p_provider_id
        and start_at < v_slot_end
        and end_at > v_slot_start
    ) and v_slot_start > now() then
      slot_start := v_slot_start;
      slot_end := v_slot_end;
      return next;
    end if;

    v_slot_start := v_slot_start + v_step;
  end loop;
end;
$$;

-- search_providers
CREATE OR REPLACE FUNCTION public.search_providers(
  p_categories text[] DEFAULT NULL,
  p_query text DEFAULT NULL,
  p_offset integer DEFAULT 0,
  p_limit integer DEFAULT 20
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
declare
  v_result json;
begin
  select json_agg(row_to_json(t)) into v_result
  from (
    select
      p.slug,
      p.name,
      p.bio,
      p.icon_url,
      p.category,
      p.brand_color
    from public.providers p
    where p.is_active = true
      and exists (
        select 1 from public.services s
        where s.provider_id = p.id and s.is_published = true
      )
      and (p_categories is null or p.category = any(p_categories))
      and (
        p_query is null
        or p.name ilike '%' || p_query || '%'
        or p.bio ilike '%' || p_query || '%'
      )
    order by p.id desc
    offset p_offset
    limit p_limit
  ) t;

  return coalesce(v_result, '[]'::json);
end;
$$;
