-- Sprint 4 CU-1: customer_notes テーブル作成 + provider_settings にカスタム項目ラベルカラム追加

-- customer_notes テーブル
CREATE TABLE public.customer_notes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider_id bigint NOT NULL REFERENCES public.providers(id),
  customer_user_id bigint NOT NULL REFERENCES public.users(id),
  memo text,
  custom_fields jsonb DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(provider_id, customer_user_id)
);

-- RLS 有効化
ALTER TABLE public.customer_notes ENABLE ROW LEVEL SECURITY;

-- 自分の顧客データのみ読み書き可能
CREATE POLICY customer_notes_select_own ON public.customer_notes
  FOR SELECT USING (
    provider_id IN (
      SELECT p.id FROM providers p
      JOIN users u ON u.id = p.user_id
      WHERE u.auth_uid = auth.uid()
    )
  );

CREATE POLICY customer_notes_insert_own ON public.customer_notes
  FOR INSERT WITH CHECK (
    provider_id IN (
      SELECT p.id FROM providers p
      JOIN users u ON u.id = p.user_id
      WHERE u.auth_uid = auth.uid()
    )
  );

CREATE POLICY customer_notes_update_own ON public.customer_notes
  FOR UPDATE USING (
    provider_id IN (
      SELECT p.id FROM providers p
      JOIN users u ON u.id = p.user_id
      WHERE u.auth_uid = auth.uid()
    )
  );

CREATE POLICY customer_notes_delete_own ON public.customer_notes
  FOR DELETE USING (
    provider_id IN (
      SELECT p.id FROM providers p
      JOIN users u ON u.id = p.user_id
      WHERE u.auth_uid = auth.uid()
    )
  );

-- provider_settings にカスタム項目ラベルカラムを追加
ALTER TABLE public.provider_settings
  ADD COLUMN customer_custom_labels jsonb DEFAULT '[]'::jsonb;

COMMENT ON TABLE public.customer_notes IS '顧客メモ・カスタム項目（事業主ごと）';
COMMENT ON COLUMN public.provider_settings.customer_custom_labels IS 'カスタム項目ラベル（最大3つ）: ["アレルギー", "好みのスタイル", "備考"]';
